### ISSUE TITLE
Bug: not all domains retrieved

### ISSUE THREAD

**Issue by osoviejo** [leandrokoiti/GoDaddyDnsUpdater#1]
First, thanks much for writing this--should be getting more love than it is.

I have eight domains on my GoDaddy account with A records.  The app picked up seven.  Have no idea why it skipped one.

Edit: It appears this is on GoDaddy, which is not returning info on the missing domain.  Odd, as it works fine in all other respects.  I'll inquire.

**Comment by osoviejo** [comment]
Okay, here's the story.  GoDaddy's /v1/domains API has an internal value of 100 for the "limit" parameter, rather than the expected (at least by me) "return everything" if no limit is specified.

It gets worse.  This limit (whether specified or implied) doesn't determine the number of records returned to the client--it's instead the number of records returned internally before any filtering (like statuses=ACTIVE) is applied.  This list includes **all** domains the user has ever registered with GoDaddy.

In my case--stretching back 20 years--that's well over 100 domains.  But only eight of those remain active.  That entire list first gets truncated to 100, which cuts off one of the active domains, and then the ACTIVE filter is applied, returning seven domains instead of eight.

My suggestion would be to add an explicit "limit=10000" parameter to the query string on the call.  This is tested and works fine.

**Comment by leandrokoiti** [comment]
Hey @osoviejo , thanks a lot, I'm glad it's being useful to you as well and sorry for taking this long to reply. 

By reading your latest findings I believe adding an explicit parameter would be the way to go right now, I'm going to read the API documentation to check if we can solve this issue some other way.

Anyway, I will update the code and release a new version this weekend as soon as I can turn my PC on at home and update the code here on github, please feel free to change anything if you need as well, I will be more than happy to merge, thanks a lot for the help!

**Comment by leandrokoiti** [comment]
Well... I couldn't find anywhere in their documentation the maximum allowed by the "limit" parameter, I've tried a few values and the maximum I could set was 1,000,000 so I changed the "ListDomains" method to always include this limit value, can you check version 1.0.2 if you can see all of your active domains now? Thanks again

**Comment by osoviejo** [comment]
Did the trick, thanks a bunch!

**Comment by leandrokoiti** [comment]
Nice, gonna close this one then!
